name: "MyParkingSystemWorkflow"
dataIns:
  - name: "all_tweets"
    type: "collection"
    source: "all_tweets"
  - name: "desired_num_batches"
    type: "number"
    source: "desired_num_batches"
  - name: "inference_type"
    type: "string"
    source: "inference_type"
workflowBody:
  - function:
      name: "ParkingSpaceDetectionLambda"
      type: "parkingSpaceDetectionLambda"
      dataIns: []
      dataOuts: []
  - function:
      name: "FindYourCar"
      type: "findYourCar"
      dataIns:
        - name: "ticket"
          type: "Ticket"
          source: "MyParkingSystemWorkflow/all_tweets"
      dataOuts:
        - name: "carLocation"
          type: "Location"
  - function:
      name: "MobileApplicationDataProvisionLambda"
      type: "mobileAppDataProvisionLambda"
      dataIns:
        - name: "location"
          type: "Location"
          source: "MyParkingSystemWorkflow/desired_num_batches"
      dataOuts:
        - name: "parkingInfo"
          type: "ParkingAvailability"
  - function:
      name: "FireDetectionLambda"
      type: "fireDetectionLambda"
      dataIns: []
      dataOuts: []
  - function:
      name: "ParkingScoreLambda"
      type: "parkingScoreLambda"
      dataIns:
        - name: "parkingDetails"
          type: "ParkingDetails"
          source: "MyParkingSystemWorkflow/inference_type"
      dataOuts:
        - name: "score"
          type: "int"
dataOuts:
  - name: "carLocation"
    type: "Location"
    source: "FindYourCar/carLocation"
  - name: "parkingInfo"
    type: "ParkingAvailability"
    source: "MobileApplicationDataProvisionLambda/parkingInfo"
  - name: "score"
    type: "int"
    source: "ParkingScoreLambda/score"